### ISSUE TITLE
HAI601I TD1

### ISSUE THREAD

**Issue by Welzin** [Welzin/Corrections-S6#1]
Bonsoir à tous, suite à la première séance de TD/TP d'analyse syntaxique (HAI601I), j'invite tous les participants à la correction de cette matière a fournir son TD1 et TP1 [ici](/Welzin/Corrections-S6/tree/master/wip/HAI601I/TD1) pour le TD et [là](/Welzin/Corrections-S6/tree/master/wip/HAI601I/TP1) pour le TP.

Comme convenu, le commentaire des corrections sera dans 2 semaines, donc la semaine du 07-13 février.

Laissez un commentaire sous cette issue quand vous avez fourni vos corrections, et si tout le monde l'envoie avant la date prévue, on pourra avancer la review !

**Comment by Ephesiel** [comment]
J'ai ajouté ma correction du TP, plus que le TD

**Comment by Charlotte-Fabre** [comment]
**Erreur, JR-TD1** : Le quatrième AFD, pour reconnaître les littéraux numériques flottants décimaux L_f, ne reconnaît pas ceux qui ont plus d'un chiffre à gauche du point. Je dirais qu'il manque une transition [0-9] réflective sur E_dec.

**Comment by Charlotte-Fabre** [comment]
**Erreur, JR-TD1** : Le dernier automate (avec tous les langages) n'est pas déterministe puisque si la première lettre est i, on peut soit partir dans la transition vers E_i, soit dans celle vers E_id (puisque i appartient à a-z) -> Solution proposée : remplacer la transition entre E_init et E_id par [A-Za-hj-z] et créer une transition rélective [A-Za-z0-9_] sur E_i (cf image jointe)
![auto1](https://user-images.githubusercontent.com/71938946/151669797-c1556b4a-cf8f-4c37-92a5-5914d5093e24.png)

**Comment by Charlotte-Fabre** [comment]
**Erreur, MR-TD** :
1 - Deux états non-terminaux sont notés comme terminaux (double cercle) : celui qui a une transition f (pour reconnaître if) et celui qui a une transition l (pour reconnaître else)

2- Les hexadécimaux peuvent avoir un 0 après xX, les deux transitions qui permettent de les reconnaître devraient donc être [0-9,A-F,a-f] plutôt que [1-9,A-F,a-f]
L'état final du milieu (qui a une transition xX et une [0-7]) n'a pas de jeton qui en sort, il faudrait rajouter -> LITENT

3- C'est 0-9 plutôt que 1-9

4- C'est 0-9 plutôt que 1-9. 
Il y a une transition sans caractère : c'est un "." qui a été oublié

5- Il manque les " " (espaces) dans les transitions [ \t\n].
Dans la dernière ligne de l'automate, la transition qui va du deuxième état vers le premier devrait être [^/*] plutôt que [^*], sinon l'automate n'est pas déterministe puisqu'il y a une transition / qui part du même état.

AFD Complet - Même remarque que celle faite à Johann (commentaire précédent)

**Comment by Ephesiel** [comment]
> **Erreur, JR-TD1** : Le dernier automate (avec tous les langages) n'est pas déterministe puisque si la première lettre est i, on peut soit partir dans la transition vers E_i, soit dans celle vers E_id (puisque i appartient à a-z) -> Solution proposée : remplacer la transition entre E_init et E_id par [A-Za-hj-z] et créer une transition réflective [A-Za-eg-z0-9_] sur E_i (cf image jointe)(https://user-images.githubusercontent.com/71938946/151670634-84d304f0-c7ae-4958-bb37-16496739a84f.png)

Attention la transition réflective sur E_i ne marcherait pas, il faudrait l'envoyer vers E_id. Sinon un mot comme **I**ddadzad**F** serait considéré comme un IF !
