### ISSUE TITLE
HAI602I - 7 premiers exercices

### ISSUE THREAD

**Issue by Welzin** [Welzin/Corrections-S6#2]
Bonsoir à tous, suite à la première séance de TD de calculabilité (HAI602I), j'invite tous ceux qui veulent participer à la correction des premiers exercices à la déposer [ici](/Welzin/Corrections-S6/tree/master/wip/HAI602I/TD1). Les membres du groupe B n'étant allés que jusqu'à l'exercice 6/7, on ne regardera que jusque là pour ne pas se faire spoil.

On commentera les différentes corrections d'ici maximum 2 semaines, n'oubliez pas de commenter cette issue si vous voulez déposer votre correction, et quand vous la déposez !

(les participants seront assignés pour avoir les notifications !)

**Comment by Ephesiel** [comment]
Je ferai la correction
