### ISSUE TITLE
HAI601I - TD2

### ISSUE THREAD

**Issue by Tete-de-Steak** [Welzin/Corrections-S6#6]
Le TD2 sera corrigé dans deux dimanche, le 13/02.

**Comment by berthet158** [comment]
C'est juste une remarque concernant la regex du commentaire en une ligne : 

tu fais     C1l= (  "//"  .*   \n)  or le '.' signifie tous les caractères sauf le '\n' , donc rajouter le \n à la fin ne me parait pas nécessaire.

**Comment by berthet158** [comment]
C'est juste une remarque concernant la regex du commentaire en une ligne :

tu fais C1l= ( "//" .* \n) or le '.' signifie tous les caractères sauf le '\n' , donc rajouter le \n à la fin ne me parait pas nécessaire.

**Comment by Welzin** [comment]
> C'est juste une remarque concernant la regex du commentaire en une ligne :
> 
> JR, tu fais C1l= ( "//" .* \n) or le '.' signifie tous les caractères sauf le '\n' , donc rajouter le \n à la fin ne me parait pas nécessaire.

Tu as pas tort, en fait ça dépend juste de la définition que je fais de mon commentaire. Pour moi, un commentaire `//` se termine lorsqu'il y a un caractère newline `\n`. Notre regex pour supprimer les espaces va ignorer cet `\n`, mais il se peut dans certains cas que ce soit un caractère qui défini une action, qui sait...

TL;DR : ça fait juste partie de ma définition d'un commentaire mais ce sera ignoré dans tous les cas donc c'est pas faux
