### ISSUE TITLE
HAI603I td 1 : exo 2, 4) 

### ISSUE THREAD

**Issue by Gu3Lang3** [Welzin/Corrections-S6#9]
il manque le nom de l'étape pour le passage de l'étape 2 à 3 (je suppose que c'est ^ right )

**Comment by Welzin** [comment]
En effet, bien vu, la prochaines fois tu pourras commenter directement l'issue en rapport avec la correction par contre ([ici pour celle ci par exemple](https://github.com/Welzin/Corrections-S6/issues/3))
